In [ ]:
'''
                  江城子 . 程序员之歌

              十年生死两茫茫，写程序，到天亮。
                  千行代码，Bug何处藏。
              纵使上线又怎样，朝令改，夕断肠。

              领导每天新想法，天天改，日日忙。
                  相顾无言，惟有泪千行。
              每晚灯火阑珊处，夜难寐，加班狂。

'''



In [136]:
import numpy as np
# check the number of dimensions,shape,size and data type of data
data = np.arange(12).reshape(4, 3)
print(data)
print("-----Create a 3-by-4 zero array-----")
data01 = np.zeros(12).reshape(3, 4)

print(data01)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----Create a 3-by-4 zero array-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [137]:

print("-----Create a 3-by-4 one array-----")
data02 = np.ones(12).reshape(3, 4)
print(data02)


-----Create a 3-by-4 one array-----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [138]:

print("-----Create a 5-by-2 empty array-----")
data03 = np.empty(10).reshape(5, 2)
print(data03)


-----Create a 5-by-2 empty array-----
[[3.11521375e-307 2.22520967e-307]
 [1.61323372e-307 4.67296746e-307]
 [1.69121096e-306 2.31412978e-306]
 [1.42419938e-306 7.56603881e-307]
 [8.45603440e-307 3.11510340e-307]]


In [139]:

print("-----Create an array array([ 1, 6, 11, 16]) using arrange-----")
data04 = np.arange(1, 20, 5)
print(data04)


-----Create an array array([ 1, 6, 11, 16]) using arrange-----
[ 1  6 11 16]


In [140]:

print("-----create a 2-by-3 zero array by specifying the data type as float64-----")
data05 = np.zeros(6, np.float64)
print(data05)
print("DTpey=", data05.dtype.name)


-----create a 2-by-3 zero array by specifying the data type as float64-----
[0. 0. 0. 0. 0. 0.]
DTpey= float64


In [141]:

print("-----Show the name of the data type of the array-----")
data_one = np.array([[1, 2, 3], [4, 5, 6]])
print(data_one)
print("data_one.DTpey=", data_one.dtype.name)


-----Show the name of the data type of the array-----
[[1 2 3]
 [4 5 6]]
data_one.DTpey= int32


In [142]:

print("-----Change the data type of data_one to float64-----")
data_one = data_one.astype(np.float64)
print(data_one)
print("data_one.DTpey=", data_one.dtype.name)


-----Change the data type of data_one to float64-----
[[1. 2. 3.]
 [4. 5. 6.]]
data_one.DTpey= float64


In [143]:

print(
    "-----Change the data type of float_data = np.array([1.2, 2.3, 3.5]) to int64-----")
float_data = np.array([1.2, 2.3, 3.5]).astype(np.int64)
print(float_data)
print("float_data.DTpey=", float_data.dtype.name)


-----Change the data type of float_data = np.array([1.2, 2.3, 3.5]) to int64-----
[1 2 3]
float_data.DTpey= int64


In [144]:

print(
    "-----Change the data type of str_data = np.array(['1', '2', '3']) to int64-----")
str_data = np.array(['1', '2', '3']).astype(np.int64)
print(str_data)
print("str_data.DTpey=", str_data.dtype.name)


-----Change the data type of str_data = np.array(['1', '2', '3']) to int64-----
[1 2 3]
str_data.DTpey= int64


In [145]:

print("-----Create two arrary:data1,data2-----")
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[1, 2, 3], [4, 5, 6]])
print("data1:\n", data1)
print("data2:\n", data2)


-----Create two arrary:data1,data2-----
data1:
 [[1 2 3]
 [4 5 6]]
data2:
 [[1 2 3]
 [4 5 6]]


In [146]:

print("-----(1) data1 + data2-----")
data_out = data1+data2
print("data_out:\n", data_out)


-----(1) data1 + data2-----
data_out:
 [[ 2  4  6]
 [ 8 10 12]]


In [147]:

print("-----(2) data1 * data2-----")
data_out = data1*data2
print("data_out:\n", data_out)


-----(2) data1 * data2-----
data_out:
 [[ 1  4  9]
 [16 25 36]]


In [148]:

print("-----(3) data1 - data2-----")
data_out = data1-data2
print("data_out:\n", data_out)


-----(3) data1 - data2-----
data_out:
 [[0 0 0]
 [0 0 0]]


In [149]:

print("-----(4) data1 / data2-----")
data_out = data1/data2
print("data_out:\n", data_out)


-----(4) data1 / data2-----
data_out:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [150]:

print("-----Create two arrary:arr1,arr2-----")
arr1 = np.array([[0], [1], [2], [3]])
arr2 = np.array([1, 2, 3])
print("arr1:\n", arr1)
print("arr2:\n", arr2)


-----Create two arrary:arr1,arr2-----
arr1:
 [[0]
 [1]
 [2]
 [3]]
arr2:
 [1 2 3]


In [151]:

print("-----Calculate arr1+arr2-----")
arr_out = arr1+arr2
print("arr_out:\n", arr_out)


-----Calculate arr1+arr2-----
arr_out:
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [152]:

print("-----Create two arrary:data1,data2-----")
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = 10
print("data1:\n", data1)
print("data2:\n", data2)


-----Create two arrary:data1,data2-----
data1:
 [[1 2 3]
 [4 5 6]]
data2:
 10


In [153]:


print("-----(1) data1 + data2-----")
data_out = data1+data2
print("data_out:\n", data_out)


-----(1) data1 + data2-----
data_out:
 [[11 12 13]
 [14 15 16]]


In [154]:

print("-----(2) data1 * data2-----")
data_out = data1*data2
print("data_out:\n", data_out)


-----(2) data1 * data2-----
data_out:
 [[10 20 30]
 [40 50 60]]


In [155]:

print("-----(3) data1 - data2-----")
data_out = data1-data2
print("data_out:\n", data_out)


-----(3) data1 - data2-----
data_out:
 [[-9 -8 -7]
 [-6 -5 -4]]


In [156]:

print("-----(4) data1 / data2-----")
data_out = data1/data2
print("data_out:\n", data_out)


-----(4) data1 / data2-----
data_out:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [157]:

print("-----Create an array as arr = np.arange(8)-----")
arr = np.arange(0, 8, 1)
print("arr:\n", arr)


-----Create an array as arr = np.arange(8)-----
arr:
 [0 1 2 3 4 5 6 7]


In [158]:

print("----- (1) obtain the 6th element-----")
out = arr[5]
print("out:", out)


----- (1) obtain the 6th element-----
out: 5


In [159]:

print("----- (2) obtain the 4th to 5th elements using “:” sign-----")
out = arr[3:4:1]
print("out:", out)


----- (2) obtain the 4th to 5th elements using “:” sign-----
out: [3]


In [160]:

print("----- (3) obtain the 2nd to 7th elements with a step of 2 using “:” sign-----")
out = arr[1:6:2]
print("out:", out)


----- (3) obtain the 2nd to 7th elements with a step of 2 using “:” sign-----
out: [1 3 5]


In [161]:


print(
    "-----Create an array as arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])-----")
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("arr2d:\n", arr2d)


-----Create an array as arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])-----
arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [162]:

print("----- (1) obtain the 2nd row-----")
out = arr2d[1, ...]
print("out:", out)


----- (1) obtain the 2nd row-----
out: [4 5 6]


In [163]:

print("----- (2) obtain the element of the 1st row and the 2nd column-----")
out = arr2d[0][1]
print("out:", out)


----- (2) obtain the element of the 1st row and the 2nd column-----
out: 2


In [164]:

print("----- (3) obtain the first two rows using “:” sign-----")
out = arr2d[:2]
print("out:", out)


----- (3) obtain the first two rows using “:” sign-----
out: [[1 2 3]
 [4 5 6]]


In [165]:

print(
    "----- (4) obtain the array as array([[1, 2], [4, 5]]), using “:” sign-----")
out = arr2d[0:2, 0:2]
print("out:", out)


----- (4) obtain the array as array([[1, 2], [4, 5]]), using “:” sign-----
out: [[1 2]
 [4 5]]


In [166]:

print("----- (5) obtain the array as array([4, 5]), using “:” sign-----")
out = arr2d[1:2, 0:2]
print("out:", out)


----- (5) obtain the array as array([4, 5]), using “:” sign-----
out: [[4 5]]


In [167]:

print("-----Create an array of //Obtain the two arrays using fancy indexing-----")
arr4d = np.array([[0., 1., 2., 3.], [1., 2., 3., 4.],
                 [2., 3., 4., 5.], [3., 4., 5., 6.]])
print("arr4d:\n", arr4d)


-----Create an array of //Obtain the two arrays using fancy indexing-----
arr4d:
 [[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


In [168]:

print("----- (1) array([[0., 1., 2., 3.],[2., 3., 4., 5.]])-----")
out = arr4d[[0, 2]]
print("out:\n", out)


----- (1) array([[0., 1., 2., 3.],[2., 3., 4., 5.]])-----
out:
 [[0. 1. 2. 3.]
 [2. 3. 4. 5.]]


In [169]:

print("----- (2) array([2., 5.])-----")
out = arr4d[[0, 2], [2, 3]]
print("out:\n", out)


----- (2) array([2., 5.])-----
out:
 [2. 5.]


In [170]:

print("-----Create an array of names-----")
student_name = np.array(["Tom", "Lily", "Jack", "Rose"])
print("student_name:\n", student_name)


-----Create an array of names-----
student_name:
 ['Tom' 'Lily' 'Jack' 'Rose']


In [171]:

print("-----Create a score matrix-----")
student_score = np.array(
    [[79, 88, 80], [89, 90, 92], [83, 78, 85], [78, 76, 80]])
print("student_name:\n", student_score)


-----Create a score matrix-----
student_name:
 [[79 88 80]
 [89 90 92]
 [83 78 85]
 [78 76 80]]


In [172]:

print("----- Obtain the Jack’s score using a bool array-----")
out = student_score[[False, False, True, False]]
print("out:\n", out)


----- Obtain the Jack’s score using a bool array-----
out:
 [[83 78 85]]


In [173]:

print("-----Create an array-----")
arr = np.arange(16).reshape(2, 2, 4)
print("arr:\n", arr)


-----Create an array-----
arr:
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [174]:

print("----- (1) Perform the transpose using two methods mentioned in the class-----")
out = arr.T
print("out:\n", out)
out = arr.transpose()
print("out:\n", out)


----- (1) Perform the transpose using two methods mentioned in the class-----
out:
 [[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
out:
 [[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [175]:

print("----- (2) Try arr.transpose(1, 2, 0) and write down your understanding of this operation-----")
out = arr.transpose(1, 2, 0)
print("out:\n", out)
print("自己的理解：\n0,1,2 依次代表三个方向的维度,transpose(0,1,2)这是三个维度与三个参数绑定的初始的位置，如果变换了三个参数的位置，就代表相应的维度与原来的交换了\n")


----- (2) Try arr.transpose(1, 2, 0) and write down your understanding of this operation-----
out:
 [[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]]

 [[ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]]
自己的理解：
0,1,2 依次代表三个方向的维度,transpose(0,1,2)这是三个维度与三个参数绑定的初始的位置，如果变换了三个参数的位置，就代表相应的维度与原来的交换了



In [176]:

#TODO: 翻转数组还是有点模糊
print("----- (3) Swap the axis 1 and 0-----")
out = arr.swapaxes(1,0)
print("out:\n", out)


----- (3) Swap the axis 1 and 0-----
out:
 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [177]:

print("-----Create an array -----")
x = np.array([12, 9, 13, 15])
print("x:", x)


-----Create an array -----
x: [12  9 13 15]


In [178]:

print("-----(1) calculate the square root of x-----")
out = np.sqrt(x)
print("out:", out)


-----(1) calculate the square root of x-----
out: [3.46410162 3.         3.60555128 3.87298335]


In [179]:

print("-----(2) calculate the absolute value of x-----")
out = np.abs(x)
print("out:", out)


-----(2) calculate the absolute value of x-----
out: [12  9 13 15]


In [180]:

print("-----(3) calculate the square of x-----")
out = np.square(x)
print("out:", out)


-----(3) calculate the square of x-----
out: [144  81 169 225]


In [181]:

print("-----Create two arrays: arr_x,arr_y -----")
arr_x = np.array([1,5,7])
arr_y = np.array([2,6,8])
print("arr_x:", arr_x)
print("arr_y:", arr_y)


-----Create two arrays: arr_x,arr_y -----
arr_x: [1 5 7]
arr_y: [2 6 8]


In [182]:

print("-----Use np.where() to obtain the array array([1, 6, 7])-----")
arr_con = np.array([True,False,True])
out = np.where(arr_con,arr_x,arr_y)
print("out:", out)


-----Use np.where() to obtain the array array([1, 6, 7])-----
out: [1 6 7]


In [183]:

print("-----Create an array -----")
arr = np.arange(10)
print("arr:", arr)


-----Create an array -----
arr: [0 1 2 3 4 5 6 7 8 9]


In [184]:

print("-----(1) Calculate the summation of the elements in arr-----")
out = np.sum(arr)
print("out:", out)


-----(1) Calculate the summation of the elements in arr-----
out: 45


In [185]:

print("-----(2) Calculate the average-----")
out = np.average(arr)
print("out:", out)


-----(2) Calculate the average-----
out: 4.5


In [186]:

print("-----(3) Calculate the minimal-----")
out = np.amin(arr)
print("out:", out)


-----(3) Calculate the minimal-----
out: 0


In [187]:

print("-----(4) Calculate the maximal-----")
out = np.amax(arr)
print("out:", out)


-----(4) Calculate the maximal-----
out: 9


In [188]:


print("-----Create an array -----")
arr = np.array([[6,2,7],[3,6,2],[4,3,2]])
print("arr:\n", arr)


-----Create an array -----
arr:
 [[6 2 7]
 [3 6 2]
 [4 3 2]]


In [189]:

print("-----(1) Sort each row-----")
out = np.sort(arr,1)
print("out:\n", out)


-----(1) Sort each row-----
out:
 [[2 6 7]
 [2 3 6]
 [2 3 4]]


In [190]:

print("-----(2) Sort each column-----")
out = np.sort(arr,0)
print("out:\n", out)


-----(2) Sort each column-----
out:
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


In [191]:

print("-----Create an array -----")
arr = np.array([[1,-2,-7],[-3,6,2],[-4,3,2]])
print("arr:\n", arr)


-----Create an array -----
arr:
 [[ 1 -2 -7]
 [-3  6  2]
 [-4  3  2]]


In [192]:

print("-----(1) Check if all the elements is greater than 0-----")
out = np.all(arr>0)
print("if all the elements is greater than 0? :", out)


-----(1) Check if all the elements is greater than 0-----
if all the elements is greater than 0? : False


In [193]:

print("-----(2) Check if at least one element is greater than 0-----")
out = np.any(arr>0)
print("if at least one element is greater than 0?:", out)


-----(2) Check if at least one element is greater than 0-----
if at least one element is greater than 0?: True


In [194]:

print("-----Create an array -----")
arr = np.array([12, 11, 34, 23, 12, 8, 11])
print("arr:", arr)


-----Create an array -----
arr: [12 11 34 23 12  8 11]


In [195]:

print("-----(1) find unique values-----")
out = np.unique(arr)
print("out:", out)


-----(1) find unique values-----
out: [ 8 11 12 23 34]


In [196]:

print("-----(2) each element of arr is also present in the array [11,12]-----")
out = np.in1d(arr,[11,12])
print("out:", out)


-----(2) each element of arr is also present in the array [11,12]-----
out: [ True  True False False  True False  True]


In [197]:

print("-----Create two matrix : arr_x,arr_y -----")
arr_x = np.array([[1, 2, 3], [4, 5, 6]])
arr_y = np.array([[1, 2], [3, 4], [5, 6]])
print("arr_x:\n", arr_x)
print("arr_y:\n", arr_y)


-----Create two matrix : arr_x,arr_y -----
arr_x:
 [[1 2 3]
 [4 5 6]]
arr_y:
 [[1 2]
 [3 4]
 [5 6]]


In [198]:

print("-----Calculate the matrix multiplication using three methods-----")
print("----- (1) Using dot -----")
out = np.dot(arr_x,arr_y)
print("out:\n", out)


-----Calculate the matrix multiplication using three methods-----
----- (1) Using dot -----
out:
 [[22 28]
 [49 64]]


In [199]:

print("----- (2) Using vdot -----")
out = np.vdot(arr_x,arr_y)
print("out:", out)


----- (2) Using vdot -----
out: 91


In [200]:

print("----- (3) Using matmul -----")
out = np.matmul(arr_x,arr_y)
print("out:\n", out)

----- (3) Using matmul -----
out:
 [[22 28]
 [49 64]]
